name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 当代码推送到 `master` 分支时触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 设置运行环境为 Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 拉取代码到 CI 环境
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Setup pnpm
        run: npm install -g pnpm   
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build the shared-utils project
        run: |
          pnpm build:all  # 你可以根据自己的构建命令来修改这一行
      
          
  deploy-element-ui:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/element-ui-demo/dist  # 发布目录
          destination_dir: element-ui-demo  # 部署路径
          
  deploy-element-plus:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/element-plus-demo/dist  # 发布目录
          destination_dir: element-plus-demo  # 部署路径
          
  deploy-ant-design-vue:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/ant-design-vue-demo/dist  # 发布目录
          destination_dir: ant-design-vue-demo  # 部署路径
