name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --filter=ant-design-vue-demo... --filter=element-plus-demo... --filter=element-ui-demo...
      - name: Build the project
        run: pnpm run build:github
      - name: Deploy element-ui-demo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: packages/element-ui-demo/dist
          destination_dir: element-ui-demo
      - name: Deploy element-plus-demo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: packages/element-plus-demo/dist
          destination_dir: element-plus-demo
      - name: Deploy ant-design-vue-demo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: packages/ant-design-vue-demo/dist
          destination_dir: ant-design-vue-demo
